version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: mamionmiam_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mamionmiam
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: mamionmiam_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP Browser
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: neo4j/mamionmiam
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
